version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: hi5304_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hi5304_user
      POSTGRES_PASSWORD: hi5304_password
      POSTGRES_DB: hi5304
    ports:
      - "5432:5432"
    volumes:
      - hi5304_pgdata:/var/lib/postgresql/data

volumes:
  hi5304_pgdata:






